[versions]
androidGradlePlugin = "8.3.2"
androidxActivity = "1.8.2"
androidxComposeBom = "2024.04.01"
androidxLifecycle = "2.7.0"
androidxNavigation = "2.7.7"
androidxRoom = "2.6.1"
androidxWork = "2.9.0"
composeCompiler = "1.5.11"
coroutines = "1.8.0"
daggerHilt = "2.51"
firebaseBom = "32.7.1"
material3 = "1.2.1"
mockk = "1.13.10"
truth = "1.1.5"
turbine = "1.0.0"
kotlinxSerialization = "1.6.3"
robolectric = "4.11.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-testManifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.12.0" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigation" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidxRoom" }
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidxWork" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version = "1.1.0" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }
androidx-test-core = { module = "androidx.test:core", version = "1.5.0" }
coil-compose = { module = "io.coil-kt:coil-compose", version = "2.5.0" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version = "1.23.6" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-storage = { module = "com.google.firebase:firebase-storage-ktx" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version = "1.2.0" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version = "1.2.0" }
flow-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "daggerHilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "daggerHilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.2.0" }
jvm-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
junit = { module = "junit:junit", version = "4.13.2" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version = "5.10.2" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version = "5.10.2" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.1" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.6" }
